package com.uitrs.game.majiang.web.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseReplayinfo<M extends BaseReplayinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setReplayId(java.lang.Integer replayId) {
		set("replayId", replayId);
	}

	public java.lang.Integer getReplayId() {
		return get("replayId");
	}

	public void setRecord(java.lang.String record) {
		set("record", record);
	}

	public java.lang.String getRecord() {
		return get("record");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}
}
