package com.uitrs.game.majiang.web.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * 
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		// 代理用户列表
		arp.addMapping("admininfo", "id", AdminInfo.class);
		// 代理商购买记录列表
		arp.addMapping("adminpayrecord", "id", AdminPayRecord.class);
		// 房卡类型
		arp.addMapping("cardtype", "id", CardType.class);
		// 消费记录列表
		arp.addMapping("consrecord", "id", ConsRecord.class);
		// 玩家列表
		arp.addMapping("gamerinfo", "id", GamerInfo.class);
		// 玩家充值列表
		arp.addMapping("gamerpayrecord", "id", GamerPayRecord.class);
		// 房间列表
		arp.addMapping("roominfo", "id", RoomInfo.class);
		// 游戏记录表
		arp.addMapping("gamerecord", "id", GamerRecord.class);
		// 玩家在线充值记录表
		arp.addMapping("onlinepay", "id", GamerOnline.class);
		
		arp.addMapping("replayinfo", "id", ReplayInfo.class);
		
		arp.addMapping("agent", "id", Agent.class);
		arp.addMapping("profit", "id", Profit.class);
	}
}
