package com.uitrs.game.majiang.web.model;

import com.uitrs.game.majiang.web.model.base.BaseReplayinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReplayInfo extends BaseReplayinfo<ReplayInfo> {
	public static final ReplayInfo dao = new ReplayInfo();
}
