package com.uitrs.game.majiang.web.model;

import com.uitrs.game.majiang.web.model.base.BaseRoomrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoomRecord extends BaseRoomrecord<RoomRecord> {
	public static final RoomRecord dao = new RoomRecord();
}
